services:
  # 1. CAPA DE PRESENTACIÓN (Expuesta al exterior)
  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_API_KEY=${PUBLIC_API_KEY}
    container_name: shamir-frontend
    ports:
      - "5173:80"
    networks:
      - public_net
    restart: unless-stopped
    depends_on:
      - gateway

  # 2. CAPA DE INTERMEDIACIÓN (El Puente / DMZ)
  gateway:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: shamir-gateway
    env_file:
      - .env
    networks:
      - public_net
      - private_net
    restart: unless-stopped

  # 3. CAPA DE ALMACENAMIENTO (Aislada y ciega)
  node-1:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: shamir-node-1
    command: uvicorn src.adapters.vault:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    volumes:
      - ./bovedas_locales/nodo-1:/app/data
    networks:
      - private_net
    restart: unless-stopped

  node-2:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: shamir-node-2
    command: uvicorn src.adapters.vault:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    volumes:
      - ./bovedas_locales/nodo-2:/app/data
    networks:
      - private_net
    restart: unless-stopped

  node-3:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: shamir-node-3
    command: uvicorn src.adapters.vault:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    volumes:
      - ./bovedas_locales/nodo-3:/app/data
    networks:
      - private_net
    restart: unless-stopped

  node-4:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: shamir-node-4
    command: uvicorn src.adapters.vault:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    volumes:
      - ./bovedas_locales/nodo-4:/app/data
    networks:
      - private_net
    restart: unless-stopped

  node-5:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: shamir-node-5
    command: uvicorn src.adapters.vault:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    volumes:
      - ./bovedas_locales/nodo-5:/app/data
    networks:
      - private_net
    restart: unless-stopped

# DEFINICIÓN DE LA MICROSEGMENTACIÓN ZERO TRUST
networks:
  public_net:
    driver: bridge
  private_net:
    driver: bridge
    internal: true