version: '3.8'

services:
  # El coordinador central (La cara pública)
  gateway:
    build: .
    container_name: shamir-gateway
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped

  # Las bóvedas ocultas (Sin puertos expuestos hacia afuera)
  node-1:
    build: .
    container_name: shamir-node-1
    command: uvicorn src.adapters.vault:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    restart: unless-stopped

  node-2:
    build: .
    container_name: shamir-node-2
    command: uvicorn src.adapters.vault:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    restart: unless-stopped

  node-3:
    build: .
    container_name: shamir-node-3
    command: uvicorn src.adapters.vault:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    restart: unless-stopped

  node-4:
    build: .
    container_name: shamir-node-4
    command: uvicorn src.adapters.vault:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    restart: unless-stopped

  node-5:
    build: .
    container_name: shamir-node-5
    command: uvicorn src.adapters.vault:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    restart: unless-stopped